language: node_js
node_js:
  - "10"
dist: trusty
addons:
  chrome: stable
env:
  global:
    - CC_TEST_REPORTER_ID=c786dfeddf74ea7e6ecba0ebfdb2ffd70f3182b87a59aa9bebb853511b37f7bc
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test
  - npm run bundle
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false