language: node_js
node_js:
  - "10"
dist: trusty
addons:
  chrome: stable
env:
  global:
    - CC_TEST_REPORTER_ID=1dda31768ae7aa88da7099d41f0d6e0580b67a02fc63030672ad48d1f9bbeb92

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov yarn run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false